### ISSUE TITLE
Alteração de Verbos para infinitivo nos casos de uso

### ISSUE THREAD

**Issue by thiagoiferreira** [gabrielziegler3/Requisitos-2018-1#3]
Alterar os verbos existentes nos casos de uso que não estão no infinitvo para o infinitivo.
- [x] Pagina de Tópicos
- [ ] Cada Caso de Uso
#### De preferência fazer isso no repositório local.

**Comment by joao4018** [comment]
Efetue as  mudanças na página de tópico, infelizmente não fiz no repositório local ainda falta mudar cada arquivo.
